# Generated by Django 3.1.6 on 2021-07-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='category',
            field=models.CharField(default='sss', max_length=20),
        ),
    ]
